feat: broadcast json serializable
yomorun/presencejs pull request #92
Opened 2023-09-07 14:59 UTC by luzhenqian

The only changes at the api level are the parameters of the subscribe:

```js
channel.subscribe('eventName', (payload, state) => {
  // ...
})
```

Other changes are that json strings are used internally for data transmission, and there is no change at the api level.

2023-09-07 15:21 UTC, fanweixiao requested changes
confused with what we discussed:  https://github.com/orgs/xileteam/projects/16/views/1?pane=issue&itemId=37850808

2023-09-07 15:21 UTC, fanweixiao commented on packages/presence/src/channel.ts
> +        })
```suggestion
        data: _payload
```

as the discussion: https://github.com/orgs/xileteam/discussions/672

2023-09-07 15:23 UTC, fanweixiao commented
I think should be:

```js
channel.subscribe('eventName', (payload, peer) => { // state -> peer
  // ...
})
```

2023-09-07 17:58 UTC, fanweixiao approved these changes

2023-09-08 06:13 UTC, luzhenqian commented on packages/presence/src/types.d.ts
> +
`undefined` is not standard JSON:

![image](https://github.com/yomorun/presencejs/assets/33050549/0d8525e5-a002-4270-a850-5df4c41a4cc5)

Advantages of my writing style:

More modular: By using separate types and interfaces (such as JsonPrimitive, JsonArray, and JsonObject), this way of writing provides better readability and organization.
Extensibility: If you need to modify or add annotations to a subtype in the future, the modular design can make this process easier.

2023-09-08 06:14 UTC, merged